"""initial schema

Revision ID: 215dc4d5907a
Revises:
Create Date: 2026-07-21 13:34:09.637316

Hand-written (not autogenerated) — mirrors app/models/*.py exactly, table-by-table in
FK dependency order. Written by hand because this environment has no credentialed
connection to the target Postgres instance to run --autogenerate against; the schema
below is otherwise identical to what autogenerate would have produced from the models.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "215dc4d5907a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "organizations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(200), nullable=False, unique=True),
        sa.Column("plan", sa.Enum("trial", "starter", "growth", "scale", "enterprise", name="org_plan"), nullable=False, server_default="trial"),
        sa.Column("billing_status", sa.Enum("active", "past_due", "canceled", "trialing", name="org_billing_status"), nullable=False, server_default="trialing"),
        sa.Column("stripe_customer_id", sa.String(200), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(200), nullable=True),
        sa.Column("branding_config", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_organizations_slug", "organizations", ["slug"])

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.Enum("owner", "admin", "sales_rep", name="user_role"), nullable=False, server_default="owner"),
        sa.Column("full_name", sa.String(200), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("onboarding_step", sa.Integer, nullable=False, server_default="1"),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(64), nullable=True),
        sa.Column("user_agent", sa.String(500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_sessions_user_id_expires_at", "sessions", ["user_id", "expires_at"])

    op.create_table(
        "agent_configs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False, unique=True),
        sa.Column("persona", sa.Text, nullable=False, server_default=""),
        sa.Column("qualifying_questions", postgresql.JSONB, nullable=False),
        sa.Column("guardrails", postgresql.ARRAY(sa.String), nullable=False),
        sa.Column("handoff_threshold_score", sa.Integer, nullable=False, server_default="70"),
        sa.Column("calendly_link", sa.String(500), nullable=True),
        sa.Column("system_prompt_override", sa.Text, nullable=True),
        sa.Column("active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "agent_config_history",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("agent_config_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("agent_configs.id"), nullable=False),
        sa.Column("snapshot", postgresql.JSONB, nullable=False),
        sa.Column("changed_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "lead_channels",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("channel_type", sa.Enum("website_form", "whatsapp", "email", name="channel_type"), nullable=False),
        sa.Column("config", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "leads",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("channel_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("lead_channels.id"), nullable=True),
        sa.Column("source", sa.Enum("website_form", "whatsapp", "email", "demo_sandbox", name="lead_source"), nullable=False),
        sa.Column("contact_name", sa.String(200), nullable=False),
        sa.Column("contact_email", sa.String(320), nullable=True),
        sa.Column("contact_phone", sa.String(32), nullable=True),
        sa.Column("status", sa.Enum("new", "qualified", "booked", "rejected", name="lead_status"), nullable=False, server_default="new"),
        sa.Column("budget", sa.Text, nullable=True),
        sa.Column("timeline", sa.Text, nullable=True),
        sa.Column("need", sa.Text, nullable=True),
        sa.Column("company_size", sa.Text, nullable=True),
        sa.Column("decision_authority", sa.Boolean, nullable=True),
        sa.Column("qualification_score", sa.Integer, nullable=True),
        sa.Column("qualification_answers", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("rejection_reason", sa.Text, nullable=True),
        sa.Column("calendly_booking_url", sa.String(500), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_time_seconds", sa.Integer, nullable=True),
        sa.Column("booked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_demo", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("assigned_rep_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_leads_org_status_created", "leads", ["organization_id", "status", "created_at"])

    op.create_table(
        "conversations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("leads.id"), nullable=False, unique=True),
        sa.Column("status", sa.Enum("active", "completed", "handed_off", name="conversation_status"), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("conversations.id"), nullable=False),
        sa.Column("role", sa.Enum("lead", "agent", "system", name="message_role"), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("channel", sa.Enum("website_form", "whatsapp", "email", name="message_channel"), nullable=False),
        sa.Column("message_metadata", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_messages_conversation_created", "messages", ["conversation_id", "created_at"])

    op.create_table(
        "notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("lead_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("leads.id"), nullable=True),
        sa.Column("type", sa.Enum("lead_qualified", "lead_booked", "lead_rejected", "weekly_summary", name="notification_type"), nullable=False),
        sa.Column("channel", sa.Enum("email", name="notification_channel"), nullable=False, server_default="email"),
        sa.Column("status", sa.Enum("pending", "sent", "failed", name="notification_status"), nullable=False, server_default="pending"),
        sa.Column("payload", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "contact_submissions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("company", sa.String(200), nullable=True),
        sa.Column("message", sa.Text, nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "integrations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("provider", sa.Enum("calendly", "slack", "hubspot", name="integration_provider"), nullable=False),
        sa.Column("credentials_encrypted", sa.LargeBinary, nullable=True),
        sa.Column("status", sa.Enum("connected", "error", "disconnected", name="integration_status"), nullable=False, server_default="disconnected"),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("action", sa.String(200), nullable=False),
        sa.Column("target_type", sa.String(100), nullable=True),
        sa.Column("target_id", sa.String(100), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # ---- Phase 2 CMS tables (see SKILL-BACKEND.md §1) ----
    op.create_table(
        "testimonials",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("quote", sa.Text, nullable=False),
        sa.Column("author_name", sa.String(200), nullable=False),
        sa.Column("author_title", sa.String(200), nullable=False),
        sa.Column("company_name", sa.String(200), nullable=False),
        sa.Column("company_logo_src", sa.String(500), nullable=True),
        sa.Column("avatar_src", sa.String(500), nullable=True),
        sa.Column("metric_callout", sa.String(200), nullable=True),
        sa.Column("is_illustrative", sa.Boolean, nullable=False, server_default=sa.true()),
    )

    op.create_table(
        "case_studies",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("slug", sa.String(150), nullable=False, unique=True),
        sa.Column("company_name", sa.String(200), nullable=False),
        sa.Column("industry", sa.String(100), nullable=False),
        sa.Column("summary", sa.Text, nullable=False),
        sa.Column("metrics", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("narrative", sa.Text, nullable=False),
        sa.Column("quote_testimonial_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("testimonials.id"), nullable=True),
        sa.Column("is_illustrative", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("published_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_case_studies_slug", "case_studies", ["slug"])

    op.create_table(
        "industries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("slug", sa.String(100), nullable=False, unique=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("meta_title", sa.String(60), nullable=False),
        sa.Column("meta_description", sa.String(155), nullable=False),
        sa.Column("hero_headline", sa.Text, nullable=False),
        sa.Column("hero_subhead", sa.Text, nullable=False),
        sa.Column("pain_points", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("case_study_slug", sa.String(100), nullable=True),
        sa.Column("faqs", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("relevant_channels", postgresql.ARRAY(sa.String), nullable=False, server_default="{}"),
        sa.Column("published_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_industries_slug", "industries", ["slug"])

    op.create_table(
        "comparisons",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("slug", sa.String(100), nullable=False, unique=True),
        sa.Column("competitor_name", sa.String(200), nullable=False),
        sa.Column("meta_title", sa.String(60), nullable=False),
        sa.Column("meta_description", sa.String(155), nullable=False),
        sa.Column("intro", sa.Text, nullable=False),
        sa.Column("feature_rows", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("when_to_choose_leadpilot", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("when_to_choose_competitor", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("faqs", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_comparisons_slug", "comparisons", ["slug"])

    op.create_table(
        "pricing_tiers",
        sa.Column("id", sa.String(50), primary_key=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("tagline", sa.String(300), nullable=False),
        sa.Column("monthly_price_cents", sa.Integer, nullable=True),
        sa.Column("annual_price_cents", sa.Integer, nullable=True),
        sa.Column("leads_included_per_month", sa.Integer, nullable=True),
        sa.Column("feature_bullets", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("highlighted", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("cta_label", sa.String(100), nullable=False),
        sa.Column("cta_href", sa.String(300), nullable=False),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"),
    )

    op.create_table(
        "blog_posts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("slug", sa.String(150), nullable=False, unique=True),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column("meta_title", sa.String(60), nullable=False),
        sa.Column("meta_description", sa.String(155), nullable=False),
        sa.Column("tldr", sa.Text, nullable=False),
        sa.Column("content_mdx", sa.Text, nullable=True),
        sa.Column("body_mdx_path", sa.String(300), nullable=True),
        sa.Column("author_name", sa.String(200), nullable=False),
        sa.Column("author_title", sa.String(200), nullable=False),
        sa.Column("author_avatar_src", sa.String(500), nullable=True),
        sa.Column("author_bio", sa.Text, nullable=False, server_default=""),
        sa.Column("tags", postgresql.ARRAY(sa.String), nullable=False, server_default="{}"),
        sa.Column("cover_image_src", sa.String(500), nullable=False, server_default=""),
        sa.Column("reading_time_minutes", sa.Integer, nullable=False, server_default="5"),
        sa.Column("faqs", postgresql.JSONB, nullable=True),
        sa.Column("related_slugs", postgresql.ARRAY(sa.String), nullable=False, server_default="{}"),
        sa.Column("status", sa.Enum("draft", "published", name="blog_status"), nullable=False, server_default="published"),
        sa.Column("published_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_blog_posts_slug", "blog_posts", ["slug"])


def downgrade() -> None:
    op.drop_table("blog_posts")
    op.drop_table("pricing_tiers")
    op.drop_table("comparisons")
    op.drop_table("industries")
    op.drop_table("case_studies")
    op.drop_table("testimonials")
    op.drop_table("audit_logs")
    op.drop_table("integrations")
    op.drop_table("contact_submissions")
    op.drop_table("notifications")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("leads")
    op.drop_table("lead_channels")
    op.drop_table("agent_config_history")
    op.drop_table("agent_configs")
    op.drop_table("sessions")
    op.drop_table("users")
    op.drop_table("organizations")

    enum_names = [
        "blog_status", "integration_status", "integration_provider", "notification_status",
        "notification_channel", "notification_type", "message_channel", "message_role",
        "conversation_status", "lead_status", "lead_source", "channel_type", "user_role",
        "org_billing_status", "org_plan",
    ]
    for name in enum_names:
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
