import asyncio
import uuid
from dataclasses import dataclass, field

from sqlalchemy.ext.asyncio import AsyncSession


@dataclass
class AgentRunContext:
    """Passed as the Agents SDK RunContextWrapper context — carries what the
    function_tools in tools.py need to actually write to the database mid-run."""

    db: AsyncSession
    organization_id: uuid.UUID
    lead_id: uuid.UUID
    conversation_id: uuid.UUID
    calendly_url: str | None
    # The Agents SDK dispatches multiple function-tool calls from the same turn
    # concurrently (asyncio.gather), but a single SQLAlchemy AsyncSession isn't safe
    # for concurrent use across tasks — without this lock, two tools both calling
    # ctx.db.add()/commit() in the same turn (e.g. record_qualification_details +
    # send_calendly_link) can interleave mid-flush and corrupt session state (observed
    # as a spurious UniqueViolationError on an autogenerated UUID primary key). Every
    # tool that touches ctx.db must acquire this before doing so.
    db_lock: asyncio.Lock = field(default_factory=asyncio.Lock)
